services:
  - type: web
    name: cleanerpro
    runtime: node
    buildCommand: rm -rf node_modules && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
